-- MySQL Script generated by MySQL Workbench
-- Qui 24 Ago 2017 18:19:15 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisdf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sisdf` ;

-- -----------------------------------------------------
-- Schema sisdf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisdf` DEFAULT CHARACTER SET utf8 ;
USE `sisdf` ;

-- -----------------------------------------------------
-- Table `cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo` ;

CREATE TABLE IF NOT EXISTS `cargo` (
  `id_cargo` INT NOT NULL,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `num_usp` INT(10) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ramal` VARCHAR(4) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `id_cargo_fk` INT NOT NULL,
  `ativo` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `num_usp_UNIQUE` (`num_usp` ASC),
  INDEX `fk_usuario_cargo1_idx` (`id_cargo_fk` ASC),
  CONSTRAINT `fk_usuario_cargo1`
    FOREIGN KEY (`id_cargo_fk`)
    REFERENCES `cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sala` ;

CREATE TABLE IF NOT EXISTS `sala` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `num_sala` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id_sala`),
  UNIQUE INDEX `num_sala_UNIQUE` (`num_sala` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `secao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secao` ;

CREATE TABLE IF NOT EXISTS `secao` (
  `id_secao` INT NOT NULL AUTO_INCREMENT,
  `nome_secao` VARCHAR(45) NOT NULL,
  `icone` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_secao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `finalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finalidade` ;

CREATE TABLE IF NOT EXISTS `finalidade` (
  `id_finalidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_finalidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `os_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `os_status` ;

CREATE TABLE IF NOT EXISTS `os_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(20) NOT NULL,
  `alias` VARCHAR(20) NOT NULL COMMENT 'Shortname para tarefas no sistema, como agrupamento e passagem para views',
  `bs_label` VARCHAR(15) NOT NULL COMMENT 'Label utilizada no bootstrap para realizar a formatação nas views de acordo com o bootstrap',
  `icone` VARCHAR(30) NOT NULL COMMENT 'Configuração da classe CSS do ícone do Font Awesome',
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ordem_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordem_servico` ;

CREATE TABLE IF NOT EXISTS `ordem_servico` (
  `id_os` INT(11) NOT NULL AUTO_INCREMENT,
  `id_relator_fk` INT(11) NOT NULL,
  `resumo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `data_abertura` DATETIME NOT NULL,
  `data_fechamento` DATETIME NULL DEFAULT NULL,
  `last_update` DATETIME NOT NULL,
  `id_atendente_fk` INT NULL DEFAULT NULL,
  `id_resp_secao_fk` INT NOT NULL,
  `id_resp_sala_fk` INT NOT NULL COMMENT 'Responsável pelo local do atendimento',
  `id_status_fk` INT NULL,
  `id_sala_fk` INT NOT NULL,
  `id_secao_fk` INT NOT NULL,
  `id_finalidade_fk` INT NOT NULL,
  PRIMARY KEY (`id_os`),
  INDEX `fk_ordem_servico_sala1_idx` (`id_sala_fk` ASC),
  INDEX `fk_ordem_servico_relator1_idx` (`id_relator_fk` ASC),
  INDEX `fk_ordem_servico_secao1_idx` (`id_secao_fk` ASC),
  INDEX `fk_ordem_servico_finalidade1_idx` (`id_finalidade_fk` ASC),
  INDEX `fk_ordem_servico_os_status1_idx` (`id_status_fk` ASC),
  INDEX `fk_ordem_servico_usuario1_idx` (`id_atendente_fk` ASC),
  INDEX `fk_ordem_servico_usuario1_idx1` (`id_resp_secao_fk` ASC),
  INDEX `fk_ordem_servico_usuario2_idx` (`id_resp_sala_fk` ASC),
  CONSTRAINT `fk_ordem_servico_sala1`
    FOREIGN KEY (`id_sala_fk`)
    REFERENCES `sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordem_servico_relator1`
    FOREIGN KEY (`id_relator_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_secao1`
    FOREIGN KEY (`id_secao_fk`)
    REFERENCES `secao` (`id_secao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_finalidade1`
    FOREIGN KEY (`id_finalidade_fk`)
    REFERENCES `finalidade` (`id_finalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_os_status1`
    FOREIGN KEY (`id_status_fk`)
    REFERENCES `os_status` (`id_status`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ordem_servico_atendente1`
    FOREIGN KEY (`id_atendente_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_resp_sec1`
    FOREIGN KEY (`id_resp_secao_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_usuario2`
    FOREIGN KEY (`id_resp_sala_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `membro_secao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membro_secao` ;

CREATE TABLE IF NOT EXISTS `membro_secao` (
  `id_usuario_fk` INT NOT NULL,
  `id_secao_fk` INT NOT NULL,
  PRIMARY KEY (`id_usuario_fk`, `id_secao_fk`),
  INDEX `fk_membro_usuario1_idx` (`id_usuario_fk` ASC),
  CONSTRAINT `fk_membros_secao1`
    FOREIGN KEY (`id_secao_fk`)
    REFERENCES `secao` (`id_secao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membro_usuario1`
    FOREIGN KEY (`id_usuario_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `anotacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anotacao` ;

CREATE TABLE IF NOT EXISTS `anotacao` (
  `id_anotacao` INT NOT NULL AUTO_INCREMENT,
  `data_anotacao` DATETIME NOT NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `id_os_fk` INT(11) NOT NULL,
  `id_usuario_fk` INT(11) NOT NULL,
  PRIMARY KEY (`id_anotacao`, `id_os_fk`),
  INDEX `fk_anotacao_ordem_servico1_idx` (`id_os_fk` ASC),
  INDEX `fk_anotacao_usuario1_idx` (`id_usuario_fk` ASC),
  CONSTRAINT `fk_anotacao_ordem_servico1`
    FOREIGN KEY (`id_os_fk`)
    REFERENCES `ordem_servico` (`id_os`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anotacao_usuario1`
    FOREIGN KEY (`id_usuario_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tipo_atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_atendimento` ;

CREATE TABLE IF NOT EXISTS `tipo_atendimento` (
  `id_tipo_atendimento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_atendimento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `os_informatica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `os_informatica` ;

CREATE TABLE IF NOT EXISTS `os_informatica` (
  `id_os_fk` INT(11) NOT NULL,
  `tipo_atendimento_fk` INT NOT NULL,
  PRIMARY KEY (`id_os_fk`, `tipo_atendimento_fk`),
  INDEX `fk_os_informatica_tipo_atendimento1_idx` (`tipo_atendimento_fk` ASC),
  CONSTRAINT `fk_os_informatica_ordem_servico1`
    FOREIGN KEY (`id_os_fk`)
    REFERENCES `ordem_servico` (`id_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_informatica_tipo_atendimento1`
    FOREIGN KEY (`tipo_atendimento_fk`)
    REFERENCES `tipo_atendimento` (`id_tipo_atendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material` ;

CREATE TABLE IF NOT EXISTS `material` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `descricao_mat` VARCHAR(255) NOT NULL,
  `fornecimento` VARCHAR(45) NOT NULL,
  `id_os_fk` INT(11) NOT NULL,
  PRIMARY KEY (`id_material`, `id_os_fk`),
  INDEX `fk_material_ordem_servico1_idx` (`id_os_fk` ASC),
  CONSTRAINT `fk_material_ordem_servico1`
    FOREIGN KEY (`id_os_fk`)
    REFERENCES `ordem_servico` (`id_os`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resp_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resp_sala` ;

CREATE TABLE IF NOT EXISTS `resp_sala` (
  `id_resp_fk` INT NOT NULL,
  `id_sala_fk` INT NOT NULL,
  PRIMARY KEY (`id_resp_fk`, `id_sala_fk`),
  INDEX `fk_responsavel_usuario1_idx` (`id_resp_fk` ASC),
  INDEX `fk_responsavel_sala1_idx` (`id_sala_fk` ASC),
  CONSTRAINT `fk_responsavel_usuario1`
    FOREIGN KEY (`id_resp_fk`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_responsavel_sala1`
    FOREIGN KEY (`id_sala_fk`)
    REFERENCES `sala` (`id_sala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL COMMENT 'Nome curto para a role no sistema',
  `role_desc` VARCHAR(150) NOT NULL COMMENT 'Descreve as funções do usuário no sistema',
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Controla o nível de acesso dos usuários';


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `usuario_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `role_id`),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  UNIQUE INDEX `user_auth` (`usuario_id` ASC, `role_id` ASC),
  CONSTRAINT `fk_user_role_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
